// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO organization.audit_events (
    id,
    organization_id,
    event_type,
    actor_kind,
    actor_identity_user_id,
    actor_membership_id,
    subject_membership_id,
    from_value,
    to_value,
    occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditEventParams struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	EventType           string
	ActorKind           string
	ActorIdentityUserID pgtype.UUID
	ActorMembershipID   pgtype.UUID
	SubjectMembershipID pgtype.UUID
	FromValue           *string
	ToValue             *string
	OccurredAt          pgtype.Timestamptz
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.OrganizationID,
		arg.EventType,
		arg.ActorKind,
		arg.ActorIdentityUserID,
		arg.ActorMembershipID,
		arg.SubjectMembershipID,
		arg.FromValue,
		arg.ToValue,
		arg.OccurredAt,
	)
	return err
}

const listOrganizationAuditEvents = `-- name: ListOrganizationAuditEvents :many
SELECT id,
       event_type,
       actor_kind,
       subject_membership_id,
       from_value,
       to_value,
       occurred_at
FROM organization.audit_events
WHERE organization_id = $1
  AND (occurred_at, id) < (
      $2::timestamptz,
      $3::uuid
  )
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type ListOrganizationAuditEventsParams struct {
	OrganizationID uuid.UUID
	BeforeTime     pgtype.Timestamptz
	BeforeID       uuid.UUID
	ResultLimit    int32
}

type ListOrganizationAuditEventsRow struct {
	ID                  uuid.UUID
	EventType           string
	ActorKind           string
	SubjectMembershipID pgtype.UUID
	FromValue           *string
	ToValue             *string
	OccurredAt          pgtype.Timestamptz
}

func (q *Queries) ListOrganizationAuditEvents(ctx context.Context, arg ListOrganizationAuditEventsParams) ([]ListOrganizationAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationAuditEvents, arg.OrganizationID, arg.BeforeTime, arg.BeforeID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationAuditEventsRow
	for rows.Next() {
		var i ListOrganizationAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorKind,
			&i.SubjectMembershipID,
			&i.FromValue,
			&i.ToValue,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
