// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listRemovalIntentsForReconciliation = `-- name: ListRemovalIntentsForReconciliation :many
SELECT r.membership_id,
       r.organization_id,
       r.created_at,
       o.clerk_organization_id,
       m.clerk_user_id
FROM organization.membership_removal_intents r
JOIN organization.memberships m
  ON m.id = r.membership_id
 AND m.organization_id = r.organization_id
JOIN organization.organizations o
  ON o.id = r.organization_id
WHERE r.created_at < $1::timestamptz
ORDER BY r.created_at ASC, r.membership_id ASC
LIMIT $2
`

type ListRemovalIntentsForReconciliationParams struct {
	Cutoff      pgtype.Timestamptz
	ResultLimit int32
}

type ListRemovalIntentsForReconciliationRow struct {
	MembershipID        uuid.UUID
	OrganizationID      uuid.UUID
	CreatedAt           pgtype.Timestamptz
	ClerkOrganizationID string
	ClerkUserID         string
}

func (q *Queries) ListRemovalIntentsForReconciliation(ctx context.Context, arg ListRemovalIntentsForReconciliationParams) ([]ListRemovalIntentsForReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listRemovalIntentsForReconciliation, arg.Cutoff, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRemovalIntentsForReconciliationRow
	for rows.Next() {
		var i ListRemovalIntentsForReconciliationRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.ClerkOrganizationID,
			&i.ClerkUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRemovalIntentForMaintenance = `-- name: LockRemovalIntentForMaintenance :one
SELECT m.id,
       m.organization_id,
       m.status
FROM organization.membership_removal_intents r
JOIN organization.memberships m
  ON m.id = r.membership_id
 AND m.organization_id = r.organization_id
WHERE r.organization_id = $1
  AND r.membership_id = $2
FOR UPDATE OF r, m
`

type LockRemovalIntentForMaintenanceParams struct {
	OrganizationID uuid.UUID
	MembershipID   uuid.UUID
}

type LockRemovalIntentForMaintenanceRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Status         string
}

func (q *Queries) LockRemovalIntentForMaintenance(ctx context.Context, arg LockRemovalIntentForMaintenanceParams) (LockRemovalIntentForMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, lockRemovalIntentForMaintenance, arg.OrganizationID, arg.MembershipID)
	var i LockRemovalIntentForMaintenanceRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Status)
	return i, err
}

const markMembershipDeletedByID = `-- name: MarkMembershipDeletedByID :exec
UPDATE organization.memberships
SET status = 'deleted'
WHERE organization_id = $1
  AND id = $2
  AND status <> 'deleted'
`

type MarkMembershipDeletedByIDParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) MarkMembershipDeletedByID(ctx context.Context, arg MarkMembershipDeletedByIDParams) error {
	_, err := q.db.Exec(ctx, markMembershipDeletedByID, arg.OrganizationID, arg.ID)
	return err
}

const pruneConsumedInvitationIntents = `-- name: PruneConsumedInvitationIntents :execrows
WITH candidates AS (
    SELECT id
    FROM organization.membership_invitation_intents
    WHERE consumed_at IS NOT NULL
      AND consumed_at < $1::timestamptz
    ORDER BY consumed_at ASC, id ASC
    LIMIT $2
)
DELETE FROM organization.membership_invitation_intents i
USING candidates c
WHERE i.id = c.id
`

type PruneConsumedInvitationIntentsParams struct {
	Cutoff      pgtype.Timestamptz
	ResultLimit int32
}

func (q *Queries) PruneConsumedInvitationIntents(ctx context.Context, arg PruneConsumedInvitationIntentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneConsumedInvitationIntents, arg.Cutoff, arg.ResultLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
