// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getActiveMembershipByOrganizationUser = `-- name: GetActiveMembershipByOrganizationUser :one
SELECT id, clerk_membership_id, organization_id, clerk_user_id, clerk_role,
       application_role, status, created_at, updated_at
FROM organization.memberships
WHERE organization_id = $1
  AND clerk_user_id = $2
  AND status = 'active'
`

type GetActiveMembershipByOrganizationUserParams struct {
	OrganizationID uuid.UUID
	ClerkUserID    string
}

func (q *Queries) GetActiveMembershipByOrganizationUser(ctx context.Context, arg GetActiveMembershipByOrganizationUserParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByOrganizationUser, arg.OrganizationID, arg.ClerkUserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.ClerkMembershipID,
		&i.OrganizationID,
		&i.ClerkUserID,
		&i.ClerkRole,
		&i.ApplicationRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByClerkID = `-- name: GetMembershipByClerkID :one
SELECT id, clerk_membership_id, organization_id, clerk_user_id, clerk_role,
       application_role, status, created_at, updated_at
FROM organization.memberships
WHERE clerk_membership_id = $1
`

func (q *Queries) GetMembershipByClerkID(ctx context.Context, clerkMembershipID string) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByClerkID, clerkMembershipID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.ClerkMembershipID,
		&i.OrganizationID,
		&i.ClerkUserID,
		&i.ClerkRole,
		&i.ApplicationRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMembership = `-- name: InsertMembership :one
INSERT INTO organization.memberships (
    id, clerk_membership_id, organization_id, clerk_user_id,
    clerk_role, application_role, status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, clerk_membership_id, organization_id, clerk_user_id, clerk_role,
          application_role, status, created_at, updated_at
`

type InsertMembershipParams struct {
	ID                uuid.UUID
	ClerkMembershipID string
	OrganizationID    uuid.UUID
	ClerkUserID       string
	ClerkRole         *string
	ApplicationRole   string
	Status            string
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, insertMembership,
		arg.ID,
		arg.ClerkMembershipID,
		arg.OrganizationID,
		arg.ClerkUserID,
		arg.ClerkRole,
		arg.ApplicationRole,
		arg.Status,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.ClerkMembershipID,
		&i.OrganizationID,
		&i.ClerkUserID,
		&i.ClerkRole,
		&i.ApplicationRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT permission_key
FROM organization.role_permissions
WHERE role_key = $1
ORDER BY permission_key
`

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleKey string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, roleKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMembershipDeleted = `-- name: MarkMembershipDeleted :one
UPDATE organization.memberships
SET status = 'deleted'
WHERE clerk_membership_id = $1
RETURNING id, clerk_membership_id, organization_id, clerk_user_id, clerk_role,
          application_role, status, created_at, updated_at
`

func (q *Queries) MarkMembershipDeleted(ctx context.Context, clerkMembershipID string) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, markMembershipDeleted, clerkMembershipID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.ClerkMembershipID,
		&i.OrganizationID,
		&i.ClerkUserID,
		&i.ClerkRole,
		&i.ApplicationRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembershipClerkRole = `-- name: UpdateMembershipClerkRole :one
UPDATE organization.memberships
SET clerk_role = $2
WHERE clerk_membership_id = $1
  AND status = 'active'
RETURNING id, clerk_membership_id, organization_id, clerk_user_id, clerk_role,
          application_role, status, created_at, updated_at
`

type UpdateMembershipClerkRoleParams struct {
	ClerkMembershipID string
	ClerkRole         *string
}

func (q *Queries) UpdateMembershipClerkRole(ctx context.Context, arg UpdateMembershipClerkRoleParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipClerkRole, arg.ClerkMembershipID, arg.ClerkRole)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.ClerkMembershipID,
		&i.OrganizationID,
		&i.ClerkUserID,
		&i.ClerkRole,
		&i.ApplicationRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
