// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership_administration.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireOrganizationAdvisoryLockByID = `-- name: AcquireOrganizationAdvisoryLockByID :exec
SELECT pg_advisory_xact_lock(hashtextextended(clerk_organization_id, 0))
FROM organization.organizations
WHERE id = $1
`

func (q *Queries) AcquireOrganizationAdvisoryLockByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acquireOrganizationAdvisoryLockByID, id)
	return err
}

const consumeMembershipInvitationIntent = `-- name: ConsumeMembershipInvitationIntent :exec
UPDATE organization.membership_invitation_intents
SET consumed_membership_id = $3,
    consumed_at = now()
WHERE organization_id = $1
  AND id = $2
  AND consumed_at IS NULL
`

type ConsumeMembershipInvitationIntentParams struct {
	OrganizationID       uuid.UUID
	ID                   uuid.UUID
	ConsumedMembershipID pgtype.UUID
}

func (q *Queries) ConsumeMembershipInvitationIntent(ctx context.Context, arg ConsumeMembershipInvitationIntentParams) error {
	_, err := q.db.Exec(ctx, consumeMembershipInvitationIntent, arg.OrganizationID, arg.ID, arg.ConsumedMembershipID)
	return err
}

const countEffectiveOwners = `-- name: CountEffectiveOwners :one
SELECT count(*)
FROM organization.memberships m
WHERE m.organization_id = $1
  AND m.status = 'active'
  AND m.application_role = 'owner'
  AND NOT EXISTS (
      SELECT 1
      FROM organization.membership_removal_intents r
      WHERE r.membership_id = m.id
  )
`

func (q *Queries) CountEffectiveOwners(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEffectiveOwners, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMembershipInvitationIntent = `-- name: DeleteMembershipInvitationIntent :exec
DELETE FROM organization.membership_invitation_intents
WHERE organization_id = $1
  AND id = $2
  AND consumed_at IS NULL
`

type DeleteMembershipInvitationIntentParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) DeleteMembershipInvitationIntent(ctx context.Context, arg DeleteMembershipInvitationIntentParams) error {
	_, err := q.db.Exec(ctx, deleteMembershipInvitationIntent, arg.OrganizationID, arg.ID)
	return err
}

const deleteMembershipRemovalIntent = `-- name: DeleteMembershipRemovalIntent :exec
DELETE FROM organization.membership_removal_intents
WHERE organization_id = $1
  AND membership_id = $2
`

type DeleteMembershipRemovalIntentParams struct {
	OrganizationID uuid.UUID
	MembershipID   uuid.UUID
}

func (q *Queries) DeleteMembershipRemovalIntent(ctx context.Context, arg DeleteMembershipRemovalIntentParams) error {
	_, err := q.db.Exec(ctx, deleteMembershipRemovalIntent, arg.OrganizationID, arg.MembershipID)
	return err
}

const getOrganizationProviderReferenceByID = `-- name: GetOrganizationProviderReferenceByID :one
SELECT id, clerk_organization_id
FROM organization.organizations
WHERE id = $1
`

type GetOrganizationProviderReferenceByIDRow struct {
	ID                  uuid.UUID
	ClerkOrganizationID string
}

func (q *Queries) GetOrganizationProviderReferenceByID(ctx context.Context, id uuid.UUID) (GetOrganizationProviderReferenceByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationProviderReferenceByID, id)
	var i GetOrganizationProviderReferenceByIDRow
	err := row.Scan(&i.ID, &i.ClerkOrganizationID)
	return i, err
}

const getPendingMembershipInvitationIntent = `-- name: GetPendingMembershipInvitationIntent :one
SELECT id, organization_id, application_role, created_by_identity_user_id,
       consumed_membership_id, consumed_at, created_at, updated_at
FROM organization.membership_invitation_intents
WHERE organization_id = $1
  AND id = $2
  AND consumed_at IS NULL
`

type GetPendingMembershipInvitationIntentParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) GetPendingMembershipInvitationIntent(ctx context.Context, arg GetPendingMembershipInvitationIntentParams) (OrganizationMembershipInvitationIntent, error) {
	row := q.db.QueryRow(ctx, getPendingMembershipInvitationIntent, arg.OrganizationID, arg.ID)
	var i OrganizationMembershipInvitationIntent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApplicationRole,
		&i.CreatedByIdentityUserID,
		&i.ConsumedMembershipID,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMembershipInvitationIntent = `-- name: InsertMembershipInvitationIntent :exec
INSERT INTO organization.membership_invitation_intents (
    id, organization_id, application_role, created_by_identity_user_id
) VALUES ($1, $2, $3, $4)
`

type InsertMembershipInvitationIntentParams struct {
	ID                      uuid.UUID
	OrganizationID          uuid.UUID
	ApplicationRole         string
	CreatedByIdentityUserID uuid.UUID
}

func (q *Queries) InsertMembershipInvitationIntent(ctx context.Context, arg InsertMembershipInvitationIntentParams) error {
	_, err := q.db.Exec(ctx, insertMembershipInvitationIntent,
		arg.ID,
		arg.OrganizationID,
		arg.ApplicationRole,
		arg.CreatedByIdentityUserID,
	)
	return err
}

const insertMembershipRemovalIntent = `-- name: InsertMembershipRemovalIntent :one
WITH target AS (
    SELECT clerk_user_id
    FROM organization.memberships
    WHERE id = $1
      AND organization_id = $2
), cancelled_bootstrap AS (
    UPDATE organization.organizations o
    SET owner_bootstrap_eligible = false
    FROM target t
    WHERE o.id = $2
      AND o.owner_bootstrap_eligible = true
      AND o.owner_bootstrapped = false
      AND o.clerk_created_by_user_id = t.clerk_user_id
)
INSERT INTO organization.membership_removal_intents (
    membership_id, organization_id, requested_by_identity_user_id
) VALUES ($1, $2, $3)
ON CONFLICT (membership_id) DO NOTHING
RETURNING membership_id
`

type InsertMembershipRemovalIntentParams struct {
	MembershipID              uuid.UUID
	OrganizationID            uuid.UUID
	RequestedByIdentityUserID uuid.UUID
}

func (q *Queries) InsertMembershipRemovalIntent(ctx context.Context, arg InsertMembershipRemovalIntentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMembershipRemovalIntent, arg.MembershipID, arg.OrganizationID, arg.RequestedByIdentityUserID)
	var membership_id uuid.UUID
	err := row.Scan(&membership_id)
	return membership_id, err
}

const lockMembershipForAdministration = `-- name: LockMembershipForAdministration :one
SELECT m.id, m.clerk_membership_id, m.organization_id, m.clerk_user_id,
       m.clerk_role, m.application_role, m.status, m.created_at, m.updated_at,
       EXISTS (
           SELECT 1
           FROM organization.membership_removal_intents r
           WHERE r.membership_id = m.id
       ) AS removal_pending
FROM organization.memberships m
WHERE m.organization_id = $1
  AND m.id = $2
FOR UPDATE OF m
`

type LockMembershipForAdministrationParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type LockMembershipForAdministrationRow struct {
	ID                uuid.UUID
	ClerkMembershipID string
	OrganizationID    uuid.UUID
	ClerkUserID       string
	ClerkRole         *string
	ApplicationRole   string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RemovalPending    bool
}

func (q *Queries) LockMembershipForAdministration(ctx context.Context, arg LockMembershipForAdministrationParams) (LockMembershipForAdministrationRow, error) {
	row := q.db.QueryRow(ctx, lockMembershipForAdministration, arg.OrganizationID, arg.ID)
	var i LockMembershipForAdministrationRow
	err := row.Scan(
		&i.ID,
		&i.ClerkMembershipID,
		&i.OrganizationID,
		&i.ClerkUserID,
		&i.ClerkRole,
		&i.ApplicationRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovalPending,
	)
	return i, err
}

const updateMembershipApplicationRoleByOrganization = `-- name: UpdateMembershipApplicationRoleByOrganization :exec
UPDATE organization.memberships
SET application_role = $3
WHERE organization_id = $1
  AND id = $2
  AND status = 'active'
`

type UpdateMembershipApplicationRoleByOrganizationParams struct {
	OrganizationID  uuid.UUID
	ID              uuid.UUID
	ApplicationRole string
}

func (q *Queries) UpdateMembershipApplicationRoleByOrganization(ctx context.Context, arg UpdateMembershipApplicationRoleByOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateMembershipApplicationRoleByOrganization, arg.OrganizationID, arg.ID, arg.ApplicationRole)
	return err
}
