// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganizationClerkWebhookEvent struct {
	EventID             string
	EventType           string
	AggregateType       string
	AggregateID         string
	ClerkOrganizationID string
	OccurredAt          pgtype.Timestamptz
	ProcessedAt         pgtype.Timestamptz
}

type OrganizationMembership struct {
	ID                uuid.UUID
	ClerkMembershipID string
	OrganizationID    uuid.UUID
	ClerkUserID       string
	ClerkRole         *string
	ApplicationRole   string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type OrganizationOrganization struct {
	ID                   uuid.UUID
	ClerkOrganizationID  string
	Name                 *string
	Slug                 *string
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LegalName            *string
	Website              *string
	Country              *string
	CompanyType          *string
	VerificationStatus   string
	TrustStatus          string
	ClerkCreatedByUserID *string
	OwnerBootstrapped    bool
}
