// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type ClerkWebhookEvent struct {
	EventID             string
	EventType           string
	AggregateType       string
	AggregateID         string
	ClerkOrganizationID string
	OccurredAt          time.Time
	ProcessedAt         time.Time
}

type Membership struct {
	ID                uuid.UUID
	ClerkMembershipID string
	OrganizationID    uuid.UUID
	ClerkUserID       string
	ClerkRole         *string
	ApplicationRole   string
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Organization struct {
	ID                  uuid.UUID
	ClerkOrganizationID string
	Name                *string
	Slug                *string
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
