// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const updateOrganizationBusinessEmailVerification = `-- name: UpdateOrganizationBusinessEmailVerification :exec
UPDATE organization.organizations
SET business_email_domain = $2,
    business_email_verified_at = $3,
    business_email_verified_by_user_id = $4
WHERE id = $1
  AND status = 'active'
`

type UpdateOrganizationBusinessEmailVerificationParams struct {
	ID                            uuid.UUID
	BusinessEmailDomain           *string
	BusinessEmailVerifiedAt       pgtype.Timestamptz
	BusinessEmailVerifiedByUserID *uuid.UUID
}

func (q *Queries) UpdateOrganizationBusinessEmailVerification(ctx context.Context, arg UpdateOrganizationBusinessEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationBusinessEmailVerification,
		arg.ID,
		arg.BusinessEmailDomain,
		arg.BusinessEmailVerifiedAt,
		arg.BusinessEmailVerifiedByUserID,
	)
	return err
}
