// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationByClerkID = `-- name: GetOrganizationByClerkID :one
SELECT id, clerk_organization_id, name, slug, status, created_at, updated_at
FROM organization.organizations
WHERE clerk_organization_id = $1
`

func (q *Queries) GetOrganizationByClerkID(ctx context.Context, clerkOrganizationID string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByClerkID, clerkOrganizationID)
	var i Organization
	err := row.Scan(&i.ID, &i.ClerkOrganizationID, &i.Name, &i.Slug, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertOrganization = `-- name: InsertOrganization :one
INSERT INTO organization.organizations (
    id, clerk_organization_id, name, slug, status
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, clerk_organization_id, name, slug, status, created_at, updated_at
`

type InsertOrganizationParams struct {
	ID                  uuid.UUID
	ClerkOrganizationID string
	Name                *string
	Slug                *string
	Status              string
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, insertOrganization, arg.ID, arg.ClerkOrganizationID, arg.Name, arg.Slug, arg.Status)
	var i Organization
	err := row.Scan(&i.ID, &i.ClerkOrganizationID, &i.Name, &i.Slug, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const markOrganizationDeleted = `-- name: MarkOrganizationDeleted :one
UPDATE organization.organizations
SET name = NULL,
    slug = NULL,
    status = 'deleted'
WHERE clerk_organization_id = $1
RETURNING id, clerk_organization_id, name, slug, status, created_at, updated_at
`

func (q *Queries) MarkOrganizationDeleted(ctx context.Context, clerkOrganizationID string) (Organization, error) {
	row := q.db.QueryRow(ctx, markOrganizationDeleted, clerkOrganizationID)
	var i Organization
	err := row.Scan(&i.ID, &i.ClerkOrganizationID, &i.Name, &i.Slug, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateOrganizationProjection = `-- name: UpdateOrganizationProjection :one
UPDATE organization.organizations
SET name = $2,
    slug = $3,
    status = CASE
        WHEN status = 'pending' THEN 'active'
        WHEN status = 'active' THEN 'active'
        ELSE status
    END
WHERE clerk_organization_id = $1
RETURNING id, clerk_organization_id, name, slug, status, created_at, updated_at
`

type UpdateOrganizationProjectionParams struct {
	ClerkOrganizationID string
	Name                *string
	Slug                *string
}

func (q *Queries) UpdateOrganizationProjection(ctx context.Context, arg UpdateOrganizationProjectionParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationProjection, arg.ClerkOrganizationID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(&i.ID, &i.ClerkOrganizationID, &i.Name, &i.Slug, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
