// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_review.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listPendingVerificationQueue = `-- name: ListPendingVerificationQueue :many
WITH pending AS (
    SELECT o.id,
           o.name,
           o.legal_name,
           o.website,
           o.country,
           o.company_type,
           o.verification_status,
           o.business_email_domain,
           o.business_email_verified_at,
           o.updated_at,
           COALESCE((
               SELECT max(a.occurred_at)
               FROM organization.audit_events a
               WHERE a.organization_id = o.id
                 AND a.event_type = 'organization.verification.requested'
           ), o.updated_at) AS requested_at
    FROM organization.organizations o
    WHERE o.status = 'active'
      AND o.verification_status = 'pending'
)
SELECT id,
       name,
       legal_name,
       website,
       country,
       company_type,
       verification_status,
       business_email_domain,
       business_email_verified_at,
       updated_at,
       requested_at
FROM pending
WHERE (requested_at, id) > (
    $1::timestamptz,
    $2::uuid
)
ORDER BY requested_at ASC, id ASC
LIMIT $3
`

type ListPendingVerificationQueueParams struct {
	AfterTime   pgtype.Timestamptz
	AfterID     uuid.UUID
	ResultLimit int32
}

type ListPendingVerificationQueueRow struct {
	ID                      uuid.UUID
	Name                    *string
	LegalName               *string
	Website                 *string
	Country                 *string
	CompanyType             *string
	VerificationStatus      string
	BusinessEmailDomain     *string
	BusinessEmailVerifiedAt pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	RequestedAt             pgtype.Timestamptz
}

func (q *Queries) ListPendingVerificationQueue(ctx context.Context, arg ListPendingVerificationQueueParams) ([]ListPendingVerificationQueueRow, error) {
	rows, err := q.db.Query(ctx, listPendingVerificationQueue, arg.AfterTime, arg.AfterID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingVerificationQueueRow
	for rows.Next() {
		var i ListPendingVerificationQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LegalName,
			&i.Website,
			&i.Country,
			&i.CompanyType,
			&i.VerificationStatus,
			&i.BusinessEmailDomain,
			&i.BusinessEmailVerifiedAt,
			&i.UpdatedAt,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
