// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlcgen

import (
	"context"
	"time"
)

const acquireOrganizationAdvisoryLock = `-- name: AcquireOrganizationAdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) AcquireOrganizationAdvisoryLock(ctx context.Context, clerkOrganizationID string) error {
	_, err := q.db.Exec(ctx, acquireOrganizationAdvisoryLock, clerkOrganizationID)
	return err
}

const getLatestAggregateEvent = `-- name: GetLatestAggregateEvent :one
SELECT event_id, event_type, aggregate_type, aggregate_id,
       clerk_organization_id, occurred_at, processed_at
FROM organization.clerk_webhook_events
WHERE aggregate_type = $1
  AND aggregate_id = $2
  AND event_id <> $3
ORDER BY occurred_at DESC,
         CASE
           WHEN event_type LIKE '%.deleted' THEN 3
           WHEN event_type LIKE '%.updated' THEN 2
           WHEN event_type LIKE '%.created' THEN 1
           ELSE 0
         END DESC,
         event_id DESC
LIMIT 1
`

type GetLatestAggregateEventParams struct {
	AggregateType string
	AggregateID   string
	EventID       string
}

func (q *Queries) GetLatestAggregateEvent(ctx context.Context, arg GetLatestAggregateEventParams) (ClerkWebhookEvent, error) {
	row := q.db.QueryRow(ctx, getLatestAggregateEvent, arg.AggregateType, arg.AggregateID, arg.EventID)
	var i ClerkWebhookEvent
	err := row.Scan(&i.EventID, &i.EventType, &i.AggregateType, &i.AggregateID, &i.ClerkOrganizationID, &i.OccurredAt, &i.ProcessedAt)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO organization.clerk_webhook_events (
    event_id, event_type, aggregate_type, aggregate_id,
    clerk_organization_id, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

type InsertWebhookEventParams struct {
	EventID             string
	EventType           string
	AggregateType       string
	AggregateID         string
	ClerkOrganizationID string
	OccurredAt          time.Time
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent, arg.EventID, arg.EventType, arg.AggregateType, arg.AggregateID, arg.ClerkOrganizationID, arg.OccurredAt)
	var eventID string
	err := row.Scan(&eventID)
	return eventID, err
}
