// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Local identity projection synchronized from Clerk.
type AppAppUser struct {
	// UUIDv7 generated by identity-service; the database does not generate this value.
	ID           uuid.UUID
	ClerkUserID  string
	PrimaryEmail *string
	// bw + 4 crypto-random digits + DDMMYY in Asia/Ho_Chi_Minh + 2 crypto-random digits.
	IDUser string
	// BridgeWorks account lifecycle, not Clerk email or magic-link verification state.
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
