// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type AppAppUser struct {
	ID           uuid.UUID
	ClerkUserID  string
	PrimaryEmail *string
	IDUser       string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
