// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_access.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformAccessAssignment = `-- name: GetPlatformAccessAssignment :one
select
    granted_at,
    revoked_at,
    updated_at
from app.platform_access_assignments
where identity_user_id = $1
  and role = $2
`

type GetPlatformAccessAssignmentParams struct {
	IdentityUserID uuid.UUID
	Role           string
}

type GetPlatformAccessAssignmentRow struct {
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetPlatformAccessAssignment(ctx context.Context, arg GetPlatformAccessAssignmentParams) (GetPlatformAccessAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getPlatformAccessAssignment, arg.IdentityUserID, arg.Role)
	var i GetPlatformAccessAssignmentRow
	err := row.Scan(&i.GrantedAt, &i.RevokedAt, &i.UpdatedAt)
	return i, err
}

const getPlatformAccessUserByClerkUserID = `-- name: GetPlatformAccessUserByClerkUserID :one
select
    id,
    status
from app.app_users
where clerk_user_id = $1
`

type GetPlatformAccessUserByClerkUserIDRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) GetPlatformAccessUserByClerkUserID(ctx context.Context, clerkUserID string) (GetPlatformAccessUserByClerkUserIDRow, error) {
	row := q.db.QueryRow(ctx, getPlatformAccessUserByClerkUserID, clerkUserID)
	var i GetPlatformAccessUserByClerkUserIDRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getPlatformAccessUserByIDUser = `-- name: GetPlatformAccessUserByIDUser :one
select
    id,
    status
from app.app_users
where id_user = $1
`

type GetPlatformAccessUserByIDUserRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) GetPlatformAccessUserByIDUser(ctx context.Context, idUser string) (GetPlatformAccessUserByIDUserRow, error) {
	row := q.db.QueryRow(ctx, getPlatformAccessUserByIDUser, idUser)
	var i GetPlatformAccessUserByIDUserRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const grantPlatformAccess = `-- name: GrantPlatformAccess :exec
insert into app.platform_access_assignments (
    identity_user_id,
    role
) values (
    $1,
    $2
)
on conflict (identity_user_id, role) do update
set
    granted_at = now(),
    revoked_at = null
where app.platform_access_assignments.revoked_at is not null
`

type GrantPlatformAccessParams struct {
	IdentityUserID uuid.UUID
	Role           string
}

func (q *Queries) GrantPlatformAccess(ctx context.Context, arg GrantPlatformAccessParams) error {
	_, err := q.db.Exec(ctx, grantPlatformAccess, arg.IdentityUserID, arg.Role)
	return err
}

const listActivePlatformRolesByUserID = `-- name: ListActivePlatformRolesByUserID :many
select role
from app.platform_access_assignments
where identity_user_id = $1
  and revoked_at is null
order by role
`

func (q *Queries) ListActivePlatformRolesByUserID(ctx context.Context, identityUserID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActivePlatformRolesByUserID, identityUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePlatformAccess = `-- name: RevokePlatformAccess :exec
update app.platform_access_assignments
set revoked_at = now()
where identity_user_id = $1
  and role = $2
  and revoked_at is null
`

type RevokePlatformAccessParams struct {
	IdentityUserID uuid.UUID
	Role           string
}

func (q *Queries) RevokePlatformAccess(ctx context.Context, arg RevokePlatformAccessParams) error {
	_, err := q.db.Exec(ctx, revokePlatformAccess, arg.IdentityUserID, arg.Role)
	return err
}
