// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getAppUserByClerkUserID = `-- name: GetAppUserByClerkUserID :one
select
    id,
    clerk_user_id,
    primary_email,
    id_user,
    status,
    created_at,
    updated_at
from app.app_users
where clerk_user_id = $1
`

func (q *Queries) GetAppUserByClerkUserID(ctx context.Context, clerkUserID string) (AppAppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByClerkUserID, clerkUserID)
	var i AppAppUser
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.PrimaryEmail,
		&i.IDUser,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAppUser = `-- name: InsertAppUser :exec
insert into app.app_users (
    id,
    clerk_user_id,
    primary_email,
    id_user,
    status
) values (
    $1,
    $2,
    $3::text::extensions.citext,
    $4,
    $5
)
`

type InsertAppUserParams struct {
	ID           uuid.UUID
	ClerkUserID  string
	PrimaryEmail *string
	IDUser       string
	Status       string
}

func (q *Queries) InsertAppUser(ctx context.Context, arg InsertAppUserParams) error {
	_, err := q.db.Exec(ctx, insertAppUser,
		arg.ID,
		arg.ClerkUserID,
		arg.PrimaryEmail,
		arg.IDUser,
		arg.Status,
	)
	return err
}

const markAppUserDeleted = `-- name: MarkAppUserDeleted :exec
update app.app_users
set
    status = 'deleted',
    primary_email = null
where clerk_user_id = $1
`

func (q *Queries) MarkAppUserDeleted(ctx context.Context, clerkUserID string) error {
	_, err := q.db.Exec(ctx, markAppUserDeleted, clerkUserID)
	return err
}

const updateAppUserPrimaryEmail = `-- name: UpdateAppUserPrimaryEmail :exec
update app.app_users
set primary_email = $1::text::extensions.citext
where clerk_user_id = $2
`

type UpdateAppUserPrimaryEmailParams struct {
	PrimaryEmail *string
	ClerkUserID  string
}

func (q *Queries) UpdateAppUserPrimaryEmail(ctx context.Context, arg UpdateAppUserPrimaryEmailParams) error {
	_, err := q.db.Exec(ctx, updateAppUserPrimaryEmail, arg.PrimaryEmail, arg.ClerkUserID)
	return err
}
