// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasSupersedingClerkWebhookEvent = `-- name: HasSupersedingClerkWebhookEvent :one
select exists (
    select 1
    from app.clerk_webhook_events
    where clerk_user_id = $1
      and event_id <> $2
      and (
          occurred_at > $3::timestamptz
          or (
              occurred_at = $3::timestamptz
              and (
                  case event_type
                      when 'user.deleted' then 3
                      when 'user.updated' then 2
                      when 'user.created' then 1
                      else 0
                  end > $4::integer
                  or (
                      case event_type
                          when 'user.deleted' then 3
                          when 'user.updated' then 2
                          when 'user.created' then 1
                          else 0
                      end = $4::integer
                      and event_id > $2
                  )
              )
          )
      )
) as has_superseding_event
`

type HasSupersedingClerkWebhookEventParams struct {
	ClerkUserID string
	EventID     string
	OccurredAt  pgtype.Timestamptz
	EventRank   int32
}

func (q *Queries) HasSupersedingClerkWebhookEvent(ctx context.Context, arg HasSupersedingClerkWebhookEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSupersedingClerkWebhookEvent,
		arg.ClerkUserID,
		arg.EventID,
		arg.OccurredAt,
		arg.EventRank,
	)
	var has_superseding_event bool
	err := row.Scan(&has_superseding_event)
	return has_superseding_event, err
}

const insertClerkWebhookEvent = `-- name: InsertClerkWebhookEvent :one
with inserted as (
    insert into app.clerk_webhook_events (
        event_id,
        event_type,
        clerk_user_id,
        occurred_at
    ) values (
        $1,
        $2,
        $3,
        $4::timestamptz
    )
    on conflict (event_id) do nothing
    returning true as inserted
)
select coalesce((select inserted from inserted), false)::boolean as inserted
`

type InsertClerkWebhookEventParams struct {
	EventID     string
	EventType   string
	ClerkUserID string
	OccurredAt  pgtype.Timestamptz
}

func (q *Queries) InsertClerkWebhookEvent(ctx context.Context, arg InsertClerkWebhookEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, insertClerkWebhookEvent,
		arg.EventID,
		arg.EventType,
		arg.ClerkUserID,
		arg.OccurredAt,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const lockClerkUser = `-- name: LockClerkUser :exec
select pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockClerkUser(ctx context.Context, clerkUserID string) error {
	_, err := q.db.Exec(ctx, lockClerkUser, clerkUserID)
	return err
}
