-- +goose Up

create schema if not exists extensions;
create extension if not exists citext with schema extensions;

create schema if not exists app;
comment on schema app is
    'Owned exclusively by BridgeWorks identity-service. Other services must not access its tables directly.';

create table app.app_users (
    id uuid primary key,
    clerk_user_id text not null,
    primary_email extensions.citext,
    id_user varchar(14) not null,
    status text not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint app_users_clerk_user_id_uq unique (clerk_user_id),
    constraint app_users_id_user_uq unique (id_user),
    constraint app_users_id_uuidv7_ck
        check (substring(id::text from 15 for 1) = '7'),
    constraint app_users_clerk_user_id_not_blank_ck
        check (btrim(clerk_user_id) <> ''),
    constraint app_users_id_user_format_ck
        check (id_user ~ '^bw[0-9]{12}$'),
    constraint app_users_status_ck
        check (status in ('active', 'disabled', 'deleted')),
    constraint app_users_timestamps_ck
        check (updated_at >= created_at)
);

comment on table app.app_users is
    'Local identity projection synchronized from Clerk.';
comment on column app.app_users.id is
    'UUIDv7 generated by identity-service; the database does not generate this value.';
comment on column app.app_users.id_user is
    'bw + 4 crypto-random digits + DDMMYY in Asia/Ho_Chi_Minh + 2 crypto-random digits.';
comment on column app.app_users.status is
    'BridgeWorks account lifecycle, not Clerk email or magic-link verification state.';

create index app_users_status_idx
    on app.app_users (status);

create table app.clerk_webhook_events (
    event_id text primary key,
    event_type text not null,
    clerk_user_id text not null,
    occurred_at timestamptz not null,
    processed_at timestamptz not null default now(),

    constraint clerk_webhook_events_event_id_not_blank_ck
        check (btrim(event_id) <> ''),
    constraint clerk_webhook_events_clerk_user_id_not_blank_ck
        check (btrim(clerk_user_id) <> ''),
    constraint clerk_webhook_events_event_type_ck
        check (event_type in ('user.created', 'user.updated', 'user.deleted'))
);

comment on table app.clerk_webhook_events is
    'Transactional inbox for idempotent processing of Clerk user webhooks. Payloads are not persisted.';

create index clerk_webhook_events_user_occurred_idx
    on app.clerk_webhook_events (clerk_user_id, occurred_at desc);

create or replace function app.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger app_users_set_updated_at
before update on app.app_users
for each row
execute function app.set_updated_at();

revoke all on schema app from public;
revoke all on table app.app_users from public;
revoke all on table app.clerk_webhook_events from public;
revoke all on function app.set_updated_at() from public;

-- +goose Down

drop trigger if exists app_users_set_updated_at on app.app_users;
drop table if exists app.clerk_webhook_events;
drop table if exists app.app_users;
drop function if exists app.set_updated_at();
